### ISSUE TITLE
Suggesttions / Improvements

### ISSUE THREAD

**Issue by inishchith** [inishchith/chaoss-microtasks#12]
- This Section is for improvements and suggestions over the microtasks performed.

**Comment by inishchith** [comment]
@valeriocos I've updated the repository with the suggestions given on each issue ticket. Please do have a look and let me know if you've got some suggestions . Thanks :)

**Comment by valeriocos** [comment]
Perfect @inishchith , I'll have a look at it today, thanks

**Comment by valeriocos** [comment]
Hi @inishchith I have just had a look to your repo. Everything looks OK, I left just a minor comment for microtask-3 https://github.com/inishchith/chaoss-microtasks/issues/4

Thank you for your work

**Comment by inishchith** [comment]
@valeriocos Thanks for the review. I've updated the repository after having a look at your comments at #4 . :)

**Comment by valeriocos** [comment]
you're welcome @inishchith :)

**Comment by inishchith** [comment]
@valeriocos I had closed some of the issues, thought they were resolved after your suggestions. Do let me know if that's okay.

**Comment by valeriocos** [comment]
They look ok, thanks for addressing my comments @inishchith
